//! Nested barrier-adapted grids for the live worst-of autocall pricer.
//!
//! Generated by `cargo run -p halcyon-quote --bin gen_nested_grids`.
//! DO NOT EDIT MANUALLY.
//!
//! Z_POS_S6[i] are normalized grid positions in units of
//! `(sigma_s6 × Z_SCALE_PER_OBS_S6[obs_rel])`. The live c-grid
//! at observation obs_rel (obs_rel = obs_idx - 1, so obs 1..5)
//! is reconstructed via:
//!     c_i = m6r(m6r(Z_POS_S6[i], sigma_s6), Z_SCALE_PER_OBS_S6[obs_rel])
//!
//! Nested subset property: for any obs_rel and K < K',
//! every position referenced by NESTED_IDX_K{K}[obs_rel] is also
//! referenced by NESTED_IDX_K{K'}[obs_rel]. This is asserted by
//! the generator and is load-bearing for the rectangular-K
//! transition matrix assembly in Phase 3.

pub const NESTED_N_OBS_REL: usize = 5;
pub const NESTED_K_REF: usize = 15;

/// Reference K=15 z-positions at SCALE_6 (shared across obs).
pub const NESTED_Z15_S6: [i64; NESTED_K_REF] = [
    -3000000, -2000000, -1500000, -1000000, -700000, -400000, -200000, 0, 200000, 400000, 700000,
    1000000, 1500000, 2000000, 3000000,
];

/// Per-observation z-scale at SCALE_6 (absorbs σ×√(obs_rel+1)×√0.5).
pub const Z_SCALE_PER_OBS_S6: [i64; NESTED_N_OBS_REL] =
    [707107, 1000000, 1224745, 1414214, 1581139];

pub const NESTED_IDX_K12: [[u8; 12]; 5] = [
    [0, 1, 2, 3, 4, 5, 7, 10, 11, 12, 13, 14],
    [0, 1, 2, 3, 4, 5, 7, 10, 11, 12, 13, 14],
    [0, 1, 2, 3, 4, 5, 7, 10, 11, 12, 13, 14],
    [0, 1, 2, 3, 4, 5, 7, 10, 11, 12, 13, 14],
    [0, 1, 2, 3, 4, 5, 7, 10, 11, 12, 13, 14],
];

pub const NESTED_IDX_K9: [[u8; 9]; 5] = [
    [0, 1, 2, 3, 5, 11, 12, 13, 14],
    [0, 1, 2, 3, 5, 11, 12, 13, 14],
    [0, 1, 2, 3, 5, 11, 12, 13, 14],
    [0, 1, 2, 3, 5, 11, 12, 13, 14],
    [0, 1, 2, 3, 5, 11, 12, 13, 14],
];

pub const NESTED_IDX_K7: [[u8; 7]; 5] = [
    [0, 2, 3, 5, 11, 13, 14],
    [0, 2, 3, 5, 11, 13, 14],
    [0, 2, 3, 5, 11, 13, 14],
    [0, 2, 3, 5, 11, 13, 14],
    [0, 2, 3, 5, 11, 13, 14],
];

pub const NESTED_IDX_K5: [[u8; 5]; 5] = [
    [0, 3, 5, 11, 14],
    [0, 3, 5, 11, 14],
    [0, 3, 5, 11, 14],
    [0, 3, 5, 11, 14],
    [0, 3, 5, 11, 14],
];

pub const NESTED_IDX_K3: [[u8; 3]; 5] =
    [[0, 3, 14], [0, 3, 14], [0, 3, 14], [0, 3, 14], [0, 3, 14]];

/// Reconstruct the c-grid (cumulative common-factor positions at SCALE_6)
/// for the given observation at the given sigma. Returns the first K entries
/// filled; the rest are zero.
#[inline(always)]
pub fn nested_c_grid(sigma_s6: i64, obs_rel: usize, k: usize) -> [i64; NESTED_K_REF] {
    let mut out = [0i64; NESTED_K_REF];
    if obs_rel >= NESTED_N_OBS_REL {
        return out;
    }
    let scale = Z_SCALE_PER_OBS_S6[obs_rel];
    let factor = sigma_s6.wrapping_mul(scale) / 1_000_000;
    match k {
        3 => {
            for i in 0..3 {
                let z = NESTED_Z15_S6[NESTED_IDX_K3[obs_rel][i] as usize];
                out[i] = z.wrapping_mul(factor) / 1_000_000;
            }
        }
        5 => {
            for i in 0..5 {
                let z = NESTED_Z15_S6[NESTED_IDX_K5[obs_rel][i] as usize];
                out[i] = z.wrapping_mul(factor) / 1_000_000;
            }
        }
        7 => {
            for i in 0..7 {
                let z = NESTED_Z15_S6[NESTED_IDX_K7[obs_rel][i] as usize];
                out[i] = z.wrapping_mul(factor) / 1_000_000;
            }
        }
        9 => {
            for i in 0..9 {
                let z = NESTED_Z15_S6[NESTED_IDX_K9[obs_rel][i] as usize];
                out[i] = z.wrapping_mul(factor) / 1_000_000;
            }
        }
        12 => {
            for i in 0..12 {
                let z = NESTED_Z15_S6[NESTED_IDX_K12[obs_rel][i] as usize];
                out[i] = z.wrapping_mul(factor) / 1_000_000;
            }
        }
        15 => {
            for i in 0..15 {
                out[i] = NESTED_Z15_S6[i].wrapping_mul(factor) / 1_000_000;
            }
        }
        _ => {}
    }
    out
}

/// Return the parent-grid index (into K=15) for position `i` in the K-subset.
#[inline(always)]
pub fn nested_parent_index(k: usize, obs_rel: usize, i: usize) -> usize {
    match k {
        3 => NESTED_IDX_K3[obs_rel][i] as usize,
        5 => NESTED_IDX_K5[obs_rel][i] as usize,
        7 => NESTED_IDX_K7[obs_rel][i] as usize,
        9 => NESTED_IDX_K9[obs_rel][i] as usize,
        12 => NESTED_IDX_K12[obs_rel][i] as usize,
        15 => i,
        _ => 0,
    }
}
